# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json

name: WebApp-MSSQL
version: 1.0.0
summary: Azure Web App Environment with SQL Server
description: Deploys an Azure Web App with SQL Server as data store
runner: ARM
templatePath: azuredeploy.json

parameters:
  - id: name
    name: Name
    description: 'Name of the Web App.'
    type: string
    required: true